version: "1.0"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    volumes:
      - ./notebooks:/notebooks
      - ./data:/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --port=6000 --allow-root

volumes:
  notebooks:
  data:
